stages:
  - docker
  - test

services:
  - docker:20.10.5-dind

variables:
  DOCKER_IMAGE_NAME: n1c0l4stournier/compliance-testing:poc

structure-test:
  stage: test
  image:
    name: docker:20.10.5
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk --no-cache add curl
    - curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 
    - chmod +x container-structure-test-linux-amd64 
    - mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test
  script:
    - docker build -t $DOCKER_IMAGE_NAME .
    - container-structure-test test --image $DOCKER_IMAGE_NAME --config structure-test.yaml -o junit --test-report report.xml
  artifacts:
    reports:
      junit: report.xml
    expire_in: 30 min
